# Generated by Django 5.0.7 on 2024-07-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pubisher',
            new_name='publisher',
        ),
    ]
