# Generated by Django 5.0.7 on 2024-07-29 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_promotion_remove_customuser_cc_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cc_expiry',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cc_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cc_num',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cvc',
        ),
    ]
