# Generated by Django 5.0.7 on 2024-07-30 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_customuser_cc_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='card_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='cvv',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='expiration_date',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='app.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
